--- INGRESAR COMO ADMINISTRADOR DE LA BDD

CONNECT / AS SYSDBA

--- INGRESAR COMO **USUARIO** (Requiere privilegios de crear sesión)
CONNECT **USUARIO** -- PIDE CONTRASEÑA DEL USUARIO;
--- DAR Y REVOCAR PRIVILEGIOS:

GRANT **PRIVILEGIO** TO **USUARIO**;
--PERMITIR REPLICACIÓN
GRANT **PRIVILEGIO** TO **USUARIO** WITH ADMIN OPTION;

REVOKE **PRIVILEGIO** FROM **USUARIO**;
--- CONFIRMAR QUE UN USUARIO EXISTE; 

SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE 'USUARIO1';
---CONFIRMAR ESTADO DE LA CUENTA
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME LIKE 'USUARIO1';
-- CONFIRMAR QUE TODOS LOS USUARIOS EXISTEN;
SELECT USERNAME FROM DBA_USERS WHERE USERNAME IN ('USUARIO1', 'USUARIO2', 'ANA');

--- CREAR USUARIO CON NOMBRE Usuario1;

CREATE USER Usuario1 IDENTIFIED BY "%%Contraseña%%";

---ELIMINAR UN USUARIO;
DROP USER **USUARIO**;

--- BLOQUEAR Y DESBLOQUEAR CUENTA DE USUARIO: 
ALTER USER **USUARIO** ACCOUNT LOCK;
ALTER USER **USUARIO** ACCOUNT UNLOCK;

